import { Inter } from 'next/font/google'
import Header from '@/component/Header'
import './globals.css'
import { PostContextProvider } from '@/MainContext/mainContext'
import { PersonalContextProvider } from '@/personalContext/personalDetailContect'
import { InfoContextProvider } from '@/infoContext/infoContext'
import { LinkContextProvider } from '@/CustomLinkContext/mainContext'
import { GallaryContextProvider } from '@/galaryContext/galaryContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Soft Tech ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <meta name="theme-color" content="#000000" />
        <title>Soft Tech Solution</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossOrigin="anonymous"></link>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
        <link href="../assets/css/nucleo-icons.css" rel="stylesheet" />
        <link href="../assets/css/nucleo-svg.css" rel="stylesheet" />
        {/* <script src="https://kit.fontawesome.com/42d5adcbca.js" crossOrigin="anonymous"></script> */}
        <link href="../assets/css/nucleo-svg.css" rel="stylesheet" />
        <link id="pagestyle" href="../assets/css/soft-ui-dashboard.css?v=1.0.7" rel="stylesheet" />

      </head>
      <body className={inter.className} style={{ background: "#f8f9fa" }} >
        <PostContextProvider>
          <PersonalContextProvider>
            <InfoContextProvider>
              <LinkContextProvider>
              <GallaryContextProvider>
             
           
            <Header />
            {children}
            </GallaryContextProvider>
            </LinkContextProvider>
            </InfoContextProvider>
          </PersonalContextProvider>
        </PostContextProvider>

      </body>
    </html>

  )
}
